In [1]:
import torch

print(f"Torch version: {torch.__version__}")
print(f"CUDA is available. {torch.cuda.is_available()}")
print(f"Device name: {torch.cuda.get_device_name(0)}")

Torch version: 2.5.1


In [9]:
# Tensor 2D - Matriz -  Definido a partir de una lista anidada python
# Modela una imagen de 2x3=6 pixels en blanco y negro
tensor2d2p3 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("- Definición")
print(tensor2d2p3)
print(f"shape: {tensor2d2p3.shape}")
print()

# Reshape a 3x2
print("- Reshape")
tensor2d3p2 = tensor2d2p3.view(3,2)
print(tensor2d3p2)
print(f"shape: {tensor2d3p2.shape}")
print()

# Matriz traspuesta de la 2x3 -> 3x2
print("- Transposición")
tensor2dt = tensor2d2p3.T
print(tensor2dt)
print(f"shape: {tensor2dt.shape}")
print()

# Producto de matrices
print("- Producto de matrices")
print(f"A = {tensor2d2p3}")
print(f"B = {tensor2d3p2}")
tensor2dp = tensor2d2p3 @ tensor2d3p2
print(f"AxB = {tensor2dp}")

- Definición
tensor([[1, 2, 3],
        [4, 5, 6]])
shape: torch.Size([2, 3])

- Reshape
tensor([[1, 2],
        [3, 4],
        [5, 6]])
shape: torch.Size([3, 2])

- Transposición
tensor([[1, 4],
        [2, 5],
        [3, 6]])
shape: torch.Size([3, 2])

- Producto de matrices
A = tensor([[1, 2, 3],
        [4, 5, 6]])
B = tensor([[1, 2],
        [3, 4],
        [5, 6]])
AxB = tensor([[22, 28],
        [49, 64]])
